# Gnome (Gnome Terminal Default)

# Default colors
[colors.primary]
background = '#1e1e1e'
foreground = '#ffffff'

# Normal colors
[colors.normal]
black      = '#171421'
red        = '#c01c28'
green      = '#26a269'
yellow     = '#a2734c'
blue       = '#12488b'
magenta    = '#a347ba'
cyan       = '#2aa1b3'
white      = '#d0cfcc'

# Bright colors
[colors.bright]
black      = '#5e5c64'
red        = '#f66151'
green      = '#33d17a'
yellow     = '#e9ad0c'
blue       = '#2a7bde'
magenta    = '#c061cb'
cyan       = '#33c7de'
white      = '#ffffff'

[font]
size = 14.0

[font.bold]
family = "FiraCode Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "FiraCode Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "FiraCode Nerd Font Mono"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Regular"

[window]
opacity = 1.0

[window.dimensions]
columns = 100
lines = 30
